GET http://127.0.0.1:5000/users

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });

    client.test("Response body is not empty", function () {
        client.assert(response.body.length > 0);
    });

    client.test("Response is JSON", function () {
        client.assert(response.headers["content-type"].includes("application/json"));
    });

    const jsonData = response.body;

    client.test("User ID exists", function () {
        client.assert(jsonData.user_id !== undefined);
    });

    client.test("Name is John", function () {
        client.assert(jsonData.name === "John");
    });

    client.test("User ID is number", function () {
        client.assert(typeof jsonData.user_id === "number");
    });

    client.test("Response time is less than 500ms", function () {
        client.assert(response.responseTime < 500);
    });
%}
